/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-11 04:46:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.BEAN.NhanVienBEAN;
import java.util.ArrayList;

public final class XemNV_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Model.BEAN.NhanVienBEAN");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Nhân Viên</title>\r\n");
      out.write("<style>\r\n");
      out.write(".csw-btn-button {\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  /*padding: 10px 35px;\r\n");
      out.write("  /*color: #ffffff !important;*/\r\n");
      out.write("  /*border-radius: 5px;\r\n");
      out.write("  /*background: #9B6A1D;*/\r\n");
      out.write("  border: 1px solid ;\r\n");
      out.write("  transition: 0.4s;\r\n");
      out.write("}\r\n");
      out.write(".csw-btn-button:hover {\r\n");
      out.write("  background: \"blue\";\r\n");
      out.write("} \r\n");
      out.write("</style>\r\n");
      out.write("    <style>\r\n");
      out.write("        a:link , a:visited{\r\n");
      out.write("            /*margin: 20px 5px;*/\r\n");
      out.write("            display: block;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: black;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("        }\r\n");
      out.write("        a:hover{\r\n");
      out.write("            border-bottom: 5px solid navy;\r\n");
      out.write("            color: navy;\r\n");
      out.write("        }\r\n");
      out.write("        .div{\r\n");
      out.write("\r\n");
      out.write("            font-size: small ;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            font-weight: inherit;\r\n");
      out.write("\r\n");
      out.write("            /*border: 1px solid lightgrey;*/\r\n");
      out.write("            background: gainsboro;\r\n");
      out.write("            padding: 0px 5px;\r\n");
      out.write("            margin: 1px 0;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<a href=\"XemNV.jsp\" target=\"\" >Xem Nhân viên</a>\r\n");
      out.write("<a href=\"XemPBServlet?action=xempb\" target=\"\">Xem Phòng ban</a>\r\n");
      out.write("<a href=\"TimKiem.jsp\" target=\"\">Tìm kiếm</a>\r\n");
      out.write("\r\n");
      out.write("<form action=\"\" method=\"post\">\r\n");
      out.write("<!-- <input type=\"submit\" name=\"themnv\" value=\"Thêm Nhân Viên\" >  -->\r\n");
      out.write("	 <input type=\"button\" name=\"themnv\" onClick=\"location.href='ThemNV.jsp'\" value=\"Thêm Nhân Viên\" src=\"ThemNV.jsp\"> \r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"deleteNVServlet\" method=\"post\">\r\n");
      out.write("	<table border=\"1\" width=\"100%\">\r\n");
      out.write("	<caption>Thông tin bảng nhân viên</caption>\r\n");
      out.write("	<TR><TH>IDNV</TH><TH>Ho Ten</TH><TH>IDPB</TH><TH>Dia chi</TH><TH>Xóa</TH></TR>\r\n");
      out.write("	");

		ArrayList<NhanVienBEAN> list = (ArrayList<NhanVienBEAN>)request.getAttribute("list");
		for(int i=0 ; i < list.size() ; i++){
	
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>");
      out.print(list.get(i).getIDNV() );
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(list.get(i).getHOTEN() );
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(list.get(i).getIDPB() );
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(list.get(i).getDIACHI() );
      out.write("</td>\r\n");
      out.write("		<td align=\"center\"><input type=\"checkbox\" name=\"check[]\" value=\"");
      out.print( list.get(i).getIDNV());
      out.write("\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("    <input type=\"submit\" value=\"Xóa Nhân Viên đã chọn\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
